import './product.dart';

final List<Product> productList = [
  Product(
    id: 0,
    name: "Mens Chronograph Watch",
    desc: "A classic and sophisticated look",
    price: 249.99,
    quantity: 0,
    image: "images/CR7.webp",
  ),
  Product(
    id: 1,
    name: "Ladies Leather Strap Watch",
    desc: "Elegant and timeless design",
    price: 149.99,
    quantity: 0,
    image: "images/goldWatch.jpeg",
  ),
  Product(
    id: 2,
    name: "Mens Digital Watch",
    desc: "Sporty and functional design",
    price: 89.99,
    quantity: 0,
    image: "images/hmoser2.jpeg",
  ),
  Product(
    id: 3,
    name: "Ladies Gold Tone Watch",
    desc: "Glamorous and sophisticated look",
    price: 199.99,
    quantity: 0,
    image: "images/iwatch.webp",
  ),
  Product(
    id: 4,
    name: "Mens Stainless Steel Watch",
    desc: "A versatile and durable timepiece",
    price: 179.99,
    quantity: 0,
    image: "images/mayweather.webp",
  ),
  Product(
    id: 5,
    name: "Ladies Rose Gold Watch",
    desc: "A stunning and feminine accessory",
    price: 149.99,
    quantity: 0,
    image: "images/metalic.webp",
  ),
  Product(
    id: 6,
    name: "Mens Leather Strap Watch",
    desc: "A classic and stylish accessory",
    price: 99.99,
    quantity: 0,
    image: "images/moser.jpeg",
  ),
  Product(
    id: 7,
    name: "Ladies Two-Tone Watch",
    desc: "A versatile and chic accessory",
    price: 129.99,
    quantity: 0,
    image: "images/pixel.jpeg",
  ),
  Product(
    id: 8,
    name: "Mens Dress Watch",
    desc: "A refined and elegant timepiece",
    price: 299.99,
    quantity: 0,
    image: "images/samsungGalaxy.jpeg",
  ),
  Product(
    id: 9,
    name: "Ladies Diamond Watch",
    desc: "A luxurious and glamorous accessory",
    price: 499.99,
    quantity: 0,
    image: "images/timex.webp",
  ),
];
